import 'dart:async';
import 'dart:io';
import 'dart:math';
import 'dart:ui';
// import 'dart:js';
import 'package:blue_thermal_printer/blue_thermal_printer.dart';
import 'package:dropdown_search/dropdown_search.dart';
import 'package:flutter/material.dart';
import 'package:easy_autocomplete/easy_autocomplete.dart';
import 'package:carousel_slider/carousel_slider.dart';
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'dart:developer';
import 'dart:io';
import 'package:path/path.dart' as path;
import 'package:image/image.dart' as img;
import 'package:qr_code_scanner/qr_code_scanner.dart';
// import 'package:barcode_scan2/barcode_scan2.dart';
import 'package:flutter/foundation.dart';
// import 'package:qrscan/qrscan.dart';
// import 'package:qr_code_scanner/qr_code_scanner.dart';
// import 'package:image/image.dart' as im;
// import 'package:flutter/widgets.dart';
import 'package:flutter_bloc/flutter_bloc.dart';
// import 'package:barcode/barcode.dart';
import 'package:url_launcher/url_launcher.dart';
import 'package:youtube_player_flutter/youtube_player_flutter.dart';

import 'package:google_mlkit_text_recognition/google_mlkit_text_recognition.dart';
import 'package:path_provider/path_provider.dart';
import 'package:permission_handler/permission_handler.dart';
import 'package:qr_flutter/qr_flutter.dart';
import 'package:visito/pages/dashboard_page/dashboard_page_bloc.dart';
import 'package:visito/pages/dashboard_page/ocr/bloc/camera_ocr_widget_bloc.dart';
import 'package:visito/pages/dashboard_page/ocr/bloc/camera_ocr_widget_veiw.dart';
import 'guess_page/guess_page_bloc.dart';
import 'test_page/testvideo_bloc.dart';
import 'package:url_launcher/url_launcher.dart';
// import 'dashboard_page/dashboard_page_bloc.dart';
import 'package:omni_datetime_picker/omni_datetime_picker.dart';
import 'list_guess_page/list_guess_page_bloc.dart';
import 'splash_page/splash_page_bloc.dart';
import 'package:auto_size_text/auto_size_text.dart';
import 'package:image_picker/image_picker.dart';
import 'package:camera/camera.dart';
import 'package:sqflite/sqflite.dart';
// import 'package:blue_thermal_printer/blue_thermal_printer.dart';
import 'package:bloc/bloc.dart';
import 'package:flutter/material.dart';
import 'package:meta/meta.dart';
// import 'package:esc_pos_utils/esc_pos_utils.dart';

// import 'package:visito/system_parameter/system_parameter_cubit.dart';

part 'dashboard_page/dashboard_page_view.dart';
part 'testt_page/testt_page_view.dart';
part 'test_page/testvideo_view.dart';
part 'list_guess_page/list_guess_page_view.dart';
part 'guess_page/guess_page_view.dart';
part 'splash_page/splash_page_view.dart';
